MARXAN-1684-cleanup-features-data
Vizzuality/marxan-cloud pull request #1179
Opened 2022-07-14 11:43 UTC by rubvalave

-Adds new method to cleanup `(geoDb)features_data` using a comparison with active `(apiDb)features`.
-Includes said method in the cleanup cron job in Geoprocessing service.

2022-07-14 14:57 UTC, hotzevzl requested changes

2022-07-14 18:22 UTC, rubvalave commented on api/apps/geoprocessing/src/modules/cleanup-tasks/cleanup-tasks.service.ts
> +      await this.geoEntityManager.query(
I just realized the previous both methods for `projects` and `scenarios` didn't include this as well. I changed and added it (though if it worked with that I'm now a little bit less confident about this working at all 😨).

2022-07-15 08:07 UTC, hotzevzl commented on api/apps/geoprocessing/src/modules/cleanup-tasks/cleanup-tasks.service.ts
> +      await this.geoEntityManager.query(
nah, that was exactly the issue with those db queries getting stuck forever - messing with data that the transaction would need, while in the transaction - so with these fixes all is nice and jolly at last (except that we may want to simplify and control the transaction a bit, but that's a different task)

2022-07-15 08:18 UTC, hotzevzl approved these changes

2022-07-15 08:18 UTC, merged