[api] Clear PU status by category
Vizzuality/marxan-cloud pull request #1346
Opened 2023-06-16 08:22 UTC by yulia-bel

## Substitute this line for a meaningful title for your changes

### Overview

_Please write a description. If the PR is hard to understand, provide a quick explanation of the code._

### Designs

_Link to the related design prototypes (if applicable)_

### Testing instructions

_Please explain how to test the PR: ID of a dataset, steps to reach the feature, etc._

### Feature relevant tickets

_Link to the related task manager tickets_

---

## Checklist before submitting

- [ ] Meaningful commits and code rebased on `develop`.
- [ ] If this PR adds feature that should be tested for regressions when
      deploying to staging/production, please add brief testing instructions
      to the deploy checklist (`docs/deployment-checklist.md`)
- [ ] Update CHANGELOG file

2023-06-20 11:09 UTC, hotzevzl requested changes
thanks @yulia-bel! Mostly all good, and well done for already doing things "the Marxan way" (or one of the several Marxan ways 😬 , but whatever).

only real recommendation is to enforce already at controller level that the kind to clear is only one of the ones we can expect and can process (and then narrow the typing of `clearLockStatus()` accordingly, too.

Plus a bunch of naming suggestions/typo checks, feel free to take your decision (on naming suggestions, not on typos 😛).

2023-06-20 11:09 UTC, hotzevzl commented on api/apps/api/src/modules/scenarios/planning-units/scenario-planning-units.service.ts
> +    return this.puRepo.find({
I usually recommend to use `return await` _always_ even when not strictly needed, mostly for the reasons put forward in this comment: https://stackoverflow.com/questions/38708550/difference-between-return-await-promise-and-return-promise#comment128897650_70198397

In practice, linters should take care of guiding us and letting us not have to keep all these details in mind. As long as the reasons for using either arrangement are clear, I have no strong opinions though.

2023-06-20 11:09 UTC, hotzevzl commented on api/apps/api/src/modules/scenarios/scenarios.service.ts
> +    kindToClear: string,
I think you could type this more strictly as
```suggestion
    kindToClear: LockStatus,
```

2023-06-20 11:09 UTC, hotzevzl commented on api/apps/api/src/modules/scenarios/scenarios.controller.ts
> +    @Param('kind') kind: string,
you could (should!) enforce that `kind` is one of the vetted `LockStatus` enum values. If it's not any of these, we can fail fast and return a 400 directly here (ideally via class-validator)

2023-06-22 07:30 UTC, yulia-bel commented
@hotzevzl thanks for the comments and suggestions - all fixed, also added one more check to geoprocessing test to cover 2 clears (include and exclude)

2023-06-22 11:54 UTC, hotzevzl commented on api/apps/api/src/modules/scenarios/scenarios.controller.ts
> +    @Param('kind') kind: LockStatus,
mind you, this will still not prevent users from requesting `DELETE /api/v1/scenarios/:scenarioId/planning-units/status/potato`: this will likely result in a no-op behind the scenes (the `scenario.planningUnitsInclusion` flow finishes without errors, and I think it just does nothing). Not a big deal since there is no error and it's unlikely to result in an exploit (hard to know without more careful analysis), and since almost all the use of this will be via the client app, which should always send meaningful values.

2023-06-22 13:23 UTC, yulia-bel commented on api/apps/api/src/modules/scenarios/scenarios.controller.ts
> +    @Param('kind') kind: LockStatus,
That's true, missed the fact that it's not the body with dto.. Thanks for pointing out - I added a small fix of validation and a test for it

2023-06-23 07:27 UTC, hotzevzl approved these changes

2023-06-23 08:49 UTC, merged