output entities migration ready + fake data for outputs
Vizzuality/marxan-cloud pull request #305
Opened 2021-06-30 17:33 UTC by aagm

Migration + fake data for outputs

2021-07-01 06:35 UTC, kgajowy requested changes
1. Failing tests 
2. We shall keep entities definitions (.entity.ts) accurate at least for columns

2021-07-01 12:02 UTC, hotzevzl reviewed
thanks @aagm, the data parts look ok, though as Kamil noted we need to sync the entities.

2021-07-01 12:02 UTC, hotzevzl commented on api/apps/geoprocessing/src/migrations/geoprocessing/1624890503611-marxanOutputEntities.ts
> +        ADD CONSTRAINT value_out_chk CHECK (value = 0 or value = 1);
do we still need `value` to be `double precision` if we constrain it to 0 or 1?

2021-07-12 06:28 UTC, kgajowy approved these changes

2021-07-12 08:27 UTC, hotzevzl commented on api/apps/geoprocessing/src/migrations/geoprocessing/1624890503611-marxanOutputEntities.ts
> +        ADD COLUMN run_id int;
we're taking care of this in https://vizzuality.atlassian.net/browse/MARXAN-498

2021-07-12 08:27 UTC, merged