feat(marxan-run): allow to cancel running process
Vizzuality/marxan-cloud pull request #308
Opened 2021-07-01 14:24 UTC by kgajowy

## Substitute this line for a meaningful title for your changes

### Overview

_Please write a description. If the PR is hard to understand, provide a quick explanation of the code._

### Designs

_Link to the related design prototypes (if applicable)_

### Testing instructions

_Please explain how to test the PR: ID of a dataset, steps to reach the feature, etc._

### Feature relevant tickets

_Link to the related task manager tickets_

---

## Checklist before submitting

- [ ] Meaningful commits and code rebased on `develop`.
- [ ] If this PR adds feature that should be tested for regressions when
      deploying to staging/production, please add brief testing instructions
      to the deploy checklist (`docs/deployment-checklist.md`)
- [ ] Update CHANGELOG file

2021-07-02 15:05 UTC, kgajowy commented
@hotzevzl still needs `clear AbortController on finish/kill/error` to be done but mainly can be reviewed.

2021-07-06 14:53 UTC, hotzevzl approved these changes

2021-07-06 14:53 UTC, hotzevzl commented on api/apps/geoprocessing/test/integration/marxan-run/marxan-run.e2e-spec.ts
> +  test(`cancellable slow marxan run`, async (done) => {
can we improve the description of this test?

2021-07-06 14:53 UTC, hotzevzl commented on api/apps/geoprocessing/test/integration/marxan-run/marxan-run.e2e-spec.ts
> +  test(`cancellable marxan run`, async (done) => {
same as above

2021-07-07 07:06 UTC, Dyostiq requested changes

2021-07-07 07:06 UTC, Dyostiq commented on api/apps/geoprocessing/test/integration/marxan-run/marxan-run.e2e-spec.ts
> +      .WhenRunningMarxan()
actually it's `GivenRunningMarxan`

2021-07-07 07:06 UTC, Dyostiq commented on api/apps/geoprocessing/src/marxan-sandboxed-runner/marxan-sandbox-runner.service.ts
> +  }
`clearAbortController`?

2021-07-07 07:07 UTC, Dyostiq approved these changes

2021-07-07 08:01 UTC, merged