feat(front): Protected areas new workflow[MARXAN-1241]
Vizzuality/marxan-cloud pull request #796
Opened 2022-02-02 18:04 UTC by anamontiaga

## Protected areas new workflow

### Overview

### Feature relevant tickets

[MARXAN-1241](https://vizzuality.atlassian.net/browse/MARXAN-1241)

2022-02-04 16:04 UTC, anamontiaga commented
So we have some problems with Protected Areas:

**API**
1 - To invalidate query and be able to update the protected areas after uploading a new custom one, we would need a new job “onUploadCustomProtectedArea” to invalidate when it succeed.

2 - We should need a PATCH instead a POST to be able to send only the threshold and not the areas + threshold. (or an other separately async job).

**FRONT**
1 - From some reason once the protected areas process is finish, the flow stands still on threshold subtab although saved subtab is planing-unit-preview

2022-02-08 08:57 UTC, mbarrenechea requested changes

2022-02-08 08:57 UTC, mbarrenechea commented on app/layout/scenarios/edit/name/component.tsx
> +            subtab: 'pu-protected-areas-preview',
At the moment we create a scenario I think the `subtab` should be null

2022-02-08 08:57 UTC, mbarrenechea commented on app/layout/scenarios/edit/wdpa/component.tsx
>                    setStep(1);
Remove `setStep`. We are going to handle everything by subtab

2022-02-08 08:57 UTC, mbarrenechea commented on app/layout/scenarios/edit/wdpa/component.tsx
>    useEffect(() => {
we don't need to handle steps anymore

2022-02-09 12:18 UTC, mbarrenechea approved these changes

2022-02-09 12:18 UTC, merged